In [1]:
import seaborn as sns

In [2]:
df=sns.load_dataset('planets')

In [3]:
df.head()

            method  number  orbital_period   mass  distance  year
0  Radial Velocity       1         269.300   7.10     77.40  2006
1  Radial Velocity       1         874.774   2.21     56.95  2008
2  Radial Velocity       1         763.000   2.60     19.84  2011
3  Radial Velocity       1         326.030  19.40    110.62  2007
4  Radial Velocity       1         516.220  10.50    119.47  2009

In [4]:
df.describe()

            number  orbital_period        mass     distance         year
count  1035.000000      992.000000  513.000000   808.000000  1035.000000
mean      1.785507     2002.917596    2.638161   264.069282  2009.070531
std       1.240976    26014.728304    3.818617   733.116493     3.972567
min       1.000000        0.090706    0.003600     1.350000  1989.000000
25%       1.000000        5.442540    0.229000    32.560000  2007.000000
50%       1.000000       39.979500    1.260000    55.250000  2010.000000
75%       2.000000      526.005000    3.040000   178.500000  2012.000000
max       7.000000   730000.000000   25.000000  8500.000000  2014.000000

In [6]:
pip install dtale

Collecting dtale
  Downloading dtale-2.8.1-py2.py3-none-any.whl (12.8 MB)
Collecting dash>=2.0.0
  Downloading dash-2.6.2-py3-none-any.whl (9.8 MB)
Requirement already satisfied: itsdangerous in f:\anaconda\lib\site-packages (from dtale) (2.0.1)
Requirement already satisfied: six in f:\anaconda\lib\site-packages (from dtale) (1.16.0)
Requirement already satisfied: xarray in f:\anaconda\lib\site-packages (from dtale) (0.20.1)
Collecting kaleido
  Downloading kaleido-0.2.1-py2.py3-none-win_amd64.whl (65.9 MB)
Collecting dash-bootstrap-components
  Downloading dash_bootstrap_components-1.2.1-py3-none-any.whl (216 kB)
Requirement already satisfied: cycler in f:\anaconda\lib\site-packages (from dtale) (0.11.0)
Collecting Flask-Compress
  Downloading Flask_Compress-1.13-py3-none-any.whl (7.9 kB)
Requirement already satisfied: plotly>=5.0.0 in f:\anaconda\lib\site-packages (from dtale) (5.6.0)
Collecting flask-ngrok
  Downloading flask_ngrok-0.0.25-py3-none-any.whl (3.1 kB)
Requirement already satisfied: numpy in f:\anaconda\lib\site-packages (from dtale) (1.21.5)
Requirement already satisfied: statsmodels in f:\anaconda\lib\site-packages (from dtale) (0.13.2)
Collecting strsimpy
  Downloading strsimpy-0.2.1-py3-none-any.whl (45 kB)
Requirement already satisfied: networkx in f:\anaconda\lib\site-packages (from dtale) (2.7.1)
Requirement already satisfied: openpyxl in f:\anaconda\lib\site-packages (from dtale) (3.0.9)
Collecting missingno<=0.4.2
  Downloading missingno-0.4.2-py3-none-any.whl (9.7 kB)
Requirement already satisfied: matplotlib in f:\anaconda\lib\site-packages (from dtale) (3.5.1)
Requirement already satisfied: seaborn in f:\anaconda\lib\site-packages (from dtale) (0.11.2)
Requirement already satisfied: xlrd in f:\anaconda\lib\site-packages (from dtale) (2.0.1)
Requirement already satisfied: pandas in f:\anaconda\lib\site-packages (from dtale) (1.4.2)
Requirement already satisfied: certifi in f:\anaconda\lib\site-packages (from dtale) (2021.10.8)
Requirement already satisfied: et-xmlfile in f:\anaconda\lib\site-packages (from dtale) (1.1.0)
Requirement already satisfied: scipy in f:\anaconda\lib\site-packages (from dtale) (1.7.3)
Requirement already satisfied: scikit-learn in f:\anaconda\lib\site-packages (from dtale) (1.0.2)
Collecting dash-daq
  Downloading dash_daq-0.5.0.tar.gz (642 kB)
Collecting lz4
  Downloading lz4-4.0.2-cp39-cp39-win_amd64.whl (98 kB)
Collecting squarify
  Downloading squarify-0.4.3-py3-none-any.whl (4.3 kB)
Collecting dash-colorscales
  Downloading dash_colorscales-0.0.4.tar.gz (62 kB)
Requirement already satisfied: requests in f:\anaconda\lib\site-packages (from dtale) (2.27.1)
Requirement already satisfied: future>=0.14.0 in f:\anaconda\lib\site-packages (from dtale) (0.18.2)
Requirement already satisfied: Flask in f:\anaconda\lib\site-packages (from dtale) (1.1.2)
Collecting dash-core-components==2.0.0
  Downloading dash_core_components-2.0.0-py3-none-any.whl (3.8 kB)
Collecting dash-html-components==2.0.0
  Downloading dash_html_components-2.0.0-py3-none-any.whl (4.1 kB)
Collecting dash-table==5.0.0
  Downloading dash_table-5.0.0-py3-none-any.whl (3.9 kB)
Requirement already satisfied: Jinja2>=2.10.1 in f:\anaconda\lib\site-packages (from Flask->dtale) (2.11.3)
Requirement already satisfied: click>=5.1 in f:\anaconda\lib\site-packages (from Flask->dtale) (8.0.4)
Requirement already satisfied: Werkzeug>=0.15 in f:\anaconda\lib\site-packages (from Flask->dtale) (2.0.3)
Requirement already satisfied: colorama in f:\anaconda\lib\site-packages (from click>=5.1->Flask->dtale) (0.4.4)
Requirement already satisfied: MarkupSafe>=0.23 in f:\anaconda\lib\site-packages (from Jinja2>=2.10.1->Flask->dtale) (2.0.1)
Requirement already satisfied: tenacity>=6.2.0 in f:\anaconda\lib\site-packages (from plotly>=5.0.0->dtale) (8.0.1)
Collecting brotli
  Downloading Brotli-1.0.9-cp39-cp39-win_amd64.whl (383 kB)
Requirement already satisfied: kiwisolver>=1.0.1 in f:\anaconda\lib\site-packages (from matplotlib->dtale) (1.3.2)
Requirement already satisfied: python-dateutil>=2.7 in f:\anaconda\lib\site-packages (from matplotlib->dtale) (2.8.2)
Requirement already satisfied: packaging>=20.0 in f:\anaconda\lib\site-packages (from matplotlib->dtale) (21.3)
Requirement already satisfied: pyparsing>=2.2.1 in f:\anaconda\lib\site-packages (from matplotlib->dtale) (3.0.4)
Requirement already satisfied: fonttools>=4.22.0 in f:\anaconda\lib\site-packages (from matplotlib->dtale) (4.25.0)
Requirement already satisfied: pillow>=6.2.0 in f:\anaconda\lib\site-packages (from matplotlib->dtale) (9.0.1)
Requirement already satisfied: pytz>=2020.1 in f:\anaconda\lib\site-packages (from pandas->dtale) (2021.3)
Requirement already satisfied: idna<4,>=2.5 in f:\anaconda\lib\site-packages (from requests->dtale) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in f:\anaconda\lib\site-packages (from requests->dtale) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in f:\anaconda\lib\site-packages (from requests->dtale) (2.0.4)
Requirement already satisfied: threadpoolctl>=2.0.0 in f:\anaconda\lib\site-packages (from scikit-learn->dtale) (2.2.0)
Requirement already satisfied: joblib>=0.11 in f:\anaconda\lib\site-packages (from scikit-learn->dtale) (1.1.0)
Requirement already satisfied: patsy>=0.5.2 in f:\anaconda\lib\site-packages (from statsmodels->dtale) (0.5.2)
Building wheels for collected packages: dash-colorscales, dash-daq
  Building wheel for dash-colorscales (setup.py): started
  Building wheel for dash-colorscales (setup.py): finished with status 'done'
  Created wheel for dash-colorscales: filename=dash_colorscales-0.0.4-py3-none-any.whl size=62582 sha256=daa41dbbe344789b6234eb78fe2c24bf07293f7a89b1f0cb31ee9c9e3640df5e
  Stored in directory: c:\users\shady\appdata\local\pip\cache\wheels\ec\32\ec\dc8a1aa820182edf280a5e26c76fc9493ae29e196735708de2
  Building wheel for dash-daq (setup.py): started
  Building wheel for dash-daq (setup.py): finished with status 'done'
  Created wheel for dash-daq: filename=dash_daq-0.5.0-py3-none-any.whl size=669714 sha256=876cdca77b35c28ffc2ad5f895cbf6141eca2e22e8c55c695d0844155fb36f8c
  Stored in directory: c:\users\shady\appdata\local\pip\cache\wheels\53\73\ea\8a422aab5cab848d88653ed3087c1fa05553c3fbd67fb6ab75
Successfully built dash-colorscales dash-daq
Installing collected packages: brotli, Flask-Compress, dash-table, dash-html-components, dash-core-components, dash, strsimpy, squarify, missingno, lz4, kaleido, flask-ngrok, dash-daq, dash-colorscales, dash-bootstrap-components, dtale
Successfully installed Flask-Compress-1.13 brotli-1.0.9 dash-2.6.2 dash-bootstrap-components-1.2.1 dash-colorscales-0.0.4 dash-core-components-2.0.0 dash-daq-0.5.0 dash-html-components-2.0.0 dash-table-5.0.0 dtale-2.8.1 flask-ngrok-0.0.25 kaleido-0.2.1 lz4-4.0.2 missingno-0.4.2 squarify-0.4.3 strsimpy-0.2.1
Note: you may need to restart the kernel to use updated packages.

In [7]:
import dtale

In [16]:
dtale.show(df)

F:\anaconda\lib\site-packages\dtale\views.py:1929: FutureWarning:

The default value of regex will change from True to False in a future version.

F:\anaconda\lib\site-packages\dtale\views.py:1929: FutureWarning:

The default value of regex will change from True to False in a future version.

F:\anaconda\lib\site-packages\dtale\views.py:1929: FutureWarning:

The default value of regex will change from True to False in a future version.

Exception occurred while processing request: Can only use .str accessor with string values!
Traceback (most recent call last):
  File "F:\anaconda\lib\site-packages\dtale\views.py", line 120, in _handle_exceptions
    return func(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\dtale\views.py", line 2708, in get_column_analysis
    return jsonify(**analysis.build())
  File "F:\anaconda\lib\site-packages\dtale\column_analysis.py", line 137, in build
    return_data, code = self.analysis.build(self)
  File "F:\anaconda\lib\site-packages\dtale\column_analysis.py", line 446, in build
    hist = self.build_hist(s, code)
  File "F:\anaconda\lib\site-packages\dtale\column_analysis.py", line 499, in build_hist
    pd.value_counts(s.str.split(expand=True).stack())
  File "F:\anaconda\lib\site-packages\pandas\core\generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
  File "F:\anaconda\lib\site-packages\pandas\core\accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "F:\anaconda\lib\site-packages\pandas\core\strings\accessor.py", line 177, in __init__
    self._inferred_dtype = self._validate(data)
  File "F:\anaconda\lib\site-packages\pandas\core\strings\accessor.py", line 231, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!

2022-10-04 21:13:34,435 - ERROR    - Exception occurred while processing request: Can only use .str accessor with string values!
Traceback (most recent call last):
  File "F:\anaconda\lib\site-packages\dtale\views.py", line 120, in _handle_exceptions
    return func(*args, **kwargs)
  File "F:\anaconda\lib\site-packages\dtale\views.py", line 2708, in get_column_analysis
    return jsonify(**analysis.build())
  File "F:\anaconda\lib\site-packages\dtale\column_analysis.py", line 137, in build
    return_data, code = self.analysis.build(self)
  File "F:\anaconda\lib\site-packages\dtale\column_analysis.py", line 446, in build
    hist = self.build_hist(s, code)
  File "F:\anaconda\lib\site-packages\dtale\column_analysis.py", line 499, in build_hist
    pd.value_counts(s.str.split(expand=True).stack())
  File "F:\anaconda\lib\site-packages\pandas\core\generic.py", line 5575, in __getattr__
    return object.__getattribute__(self, name)
  File "F:\anaconda\lib\site-packages\pandas\core\accessor.py", line 182, in __get__
    accessor_obj = self._accessor(obj)
  File "F:\anaconda\lib\site-packages\pandas\core\strings\accessor.py", line 177, in __init__
    self._inferred_dtype = self._validate(data)
  File "F:\anaconda\lib\site-packages\pandas\core\strings\accessor.py", line 231, in _validate
    raise AttributeError("Can only use .str accessor with string values!")
AttributeError: Can only use .str accessor with string values!

In [10]:
from scipy import stats

In [12]:
import numpy as np
import pandas as pd

In [14]:

if isinstance(df, (pd.DatetimeIndex, pd.MultiIndex)):
	df = df.to_frame(index=False)

# remove any pre-existing indices for ease of use in the D-Tale code, but this is not required
df = df.reset_index().drop('index', axis=1, errors='ignore')
df.columns = [str(c) for c in df.columns]  # update columns to strings in case they are numbers

chart = np.histogram(df[~pd.isnull(df['distance'])][['distance']], bins=20)
# main statistics
stats = df['distance'].describe().to_frame().T

In [15]:
stats

          count        mean         std   min    25%    50%    75%     max
distance  808.0  264.069282  733.116493  1.35  32.56  55.25  178.5  8500.0